/*
	TRANSACTION 1
    - Handles the Write(X) Operation
*/

-- Set Isolation Level
SET TRANSACTION ISOLATION LEVEL READ UNCOMMITTED;
-- SET SESSION TRANSACTION ISOLATION LEVEL READ COMMITTED;
-- SET SESSION TRANSACTION ISOLATION LEVEL REPEATABLE READ;
-- SET SESSION TRANSACTION ISOLATION LEVEL SERILIZABLE;


-- Scenario 2 (Non-repeatable Read)
-- FLOW: Execute this, while DO SLEEP(10) in Transaction 2 is running
START TRANSACTION;
	UPDATE datawarehouseho3.accounts 
    SET amount = 2.0 * amount
    WHERE id = 3;
COMMIT;